import { Task } from "@/types/app-types";
import { addDays, subDays } from "date-fns";
export const MOCK_TASKS: Task[] = [
  {
    id: "1",
    title: "Draft Project Proposal",
    priority: 1,
    status: "todo",
    dueDate: addDays(new Date(), 1).toISOString(),
    pomodoroEstimate: 4,
    pomodoroSpent: 1,
    tags: ["work", "writing"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Review Design Systems",
    priority: 2,
    status: "in-progress",
    dueDate: new Date().toISOString(),
    pomodoroEstimate: 2,
    pomodoroSpent: 0,
    tags: ["design"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Water the Plants",
    priority: 4,
    status: "completed",
    dueDate: subDays(new Date(), 1).toISOString(),
    pomodoroEstimate: 1,
    pomodoroSpent: 1,
    tags: ["home"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Prepare for Sprint Demo",
    priority: 1,
    status: "todo",
    dueDate: addDays(new Date(), 2).toISOString(),
    pomodoroEstimate: 3,
    pomodoroSpent: 0,
    tags: ["work", "meeting"],
    createdAt: new Date().toISOString(),
  },
];