import { Task } from "@/types/app-types";
import { addDays, subDays } from "date-fns";
export const MOCK_TASKS: Task[] = [
  {
    id: "1",
    title: "阅读《Attention is All You Need》论文",
    priority: 1,
    status: "todo",
    dueDate: addDays(new Date(), 1).toISOString(),
    pomodoroEstimate: 4,
    pomodoroSpent: 1,
    tags: ["工作", "学习"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "设计系统评审",
    priority: 2,
    status: "in-progress",
    dueDate: new Date().toISOString(),
    pomodoroEstimate: 2,
    pomodoroSpent: 0,
    tags: ["设计"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "给绿植浇水",
    priority: 4,
    status: "completed",
    dueDate: subDays(new Date(), 1).toISOString(),
    pomodoroEstimate: 1,
    pomodoroSpent: 1,
    tags: ["生活"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "准备冲刺演示",
    priority: 1,
    status: "todo",
    dueDate: addDays(new Date(), 2).toISOString(),
    pomodoroEstimate: 3,
    pomodoroSpent: 0,
    tags: ["工作", "会议"],
    createdAt: new Date().toISOString(),
  },
   {
    id: "5",
    title: "英语听力练习 (30分钟)",
    priority: 3,
    status: "todo",
    dueDate: addDays(new Date(), 0).toISOString(),
    pomodoroEstimate: 2,
    pomodoroSpent: 0,
    tags: ["学习"],
    createdAt: new Date().toISOString(),
  },
];