import { Task } from "@shared/types";
import { addDays, subDays } from "date-fns";
export const MOCK_TASKS: Task[] = [
  {
    id: "1",
    title: "阅读《Attention is All You Need》论文",
    priority: 1,
    status: "todo",
    type: "reading",
    dueDate: addDays(new Date(), 1).toISOString(),
    dueTime: "14:00",
    pomodoroEstimate: 4,
    pomodoroSpent: 1,
    tags: ["工作", "学习"],
    isArchived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "英语听力练习 (Section 4)",
    priority: 2,
    status: "in-progress",
    type: "listening",
    dueDate: new Date().toISOString(),
    dueTime: "10:30",
    pomodoroEstimate: 2,
    pomodoroSpent: 0,
    tags: ["学习", "托福"],
    isArchived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "给绿植浇水",
    priority: 4,
    status: "completed",
    type: "other",
    dueDate: subDays(new Date(), 1).toISOString(),
    dueTime: "08:00",
    pomodoroEstimate: 1,
    pomodoroSpent: 1,
    tags: ["生活"],
    isArchived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];